#!/usr/bin/env python

"""\
Usage:

$ source ./read_jira_credentials
$ ./next_issue
"""

import os

import requests


def help_message():
    print(__doc__)
    exit(1)


url = 'https://sighten.atlassian.net/rest/api/2/search?'

JIRA_USER = os.environ.get('JIRA_USER')
if JIRA_USER is None:
    help_message()

JQL = """
assignee = {JIRA_USER}
AND status in ("In Development", "Ready For Development")
AND issuetype != epic and sprint in opensprints()
ORDER BY status, Sprint
"""

authorization = os.environ.get('JIRA_AUTH')
if authorization is None:
    help_message()

response = requests.get(
    url,
    params={'jql': JQL.format(JIRA_USER=JIRA_USER), 'maxResults': 1},
    headers={'Authorization': authorization}
)

print(response.json()['issues'][0]['key'].lower())
