#!/usr/local/bin/fish

set issue (next_issue)
set branch razzi/$issue

if not git show-ref --quiet $branch
    git checkout origin/develop
    git checkout -b $branch
else
    git checkout $branch
end
