#!/usr/bin/env fish

set issue (next_issue); or begin
    echo Error with next_issue
    exit 1
end

set branch $JIRA_INITIALS/$issue

if not git show-ref --quiet refs/heads/$branch
    git switch -c $branch origin/develop
else
    git switch $branch
end
