#!/usr/bin/env python3

"""\
Usage:

$ source ./read_jira_credentials
$ ./next_issue
"""

import os
import sys
from json.decoder import JSONDecodeError

import requests

from lib import JIRA_API_URL, OPEN_ISSUES_JQL

process_name = sys.argv[0]


def error_out(message):
    print('{}: {}'.format(process_name, message))
    exit(1)


def help_message(env):
    print('Missing ${env}'.format(env=env))
    error_out(__doc__)


JIRA_USER = os.environ.get('JIRA_USER')
if JIRA_USER is None:
    help_message('JIRA_USER')

authorization = os.environ.get('JIRA_AUTH')
if authorization is None:
    help_message('JIRA_AUTH')

response = requests.get(
    JIRA_API_URL,
    params={'jql': OPEN_ISSUES_JQL.format(JIRA_USER=JIRA_USER), 'maxResults': 1},
    headers={'Authorization': authorization}
)

if response.status_code == 400:
    error_out('inactive account')

if response.status_code == 401:
    error_out('bad password')

try:
    print(response.json()['issues'][0]['key'].lower())
except JSONDecodeError:
    print('{}: Bad auth'.format(process_name))
    exit(1)
