#!/usr/bin/env fish
# Make sure you're sourcing this

# This does some extra work to make the password be read into a temporary
# environment variable which is cleared

read JIRA_USER -p 'echo "Jira username: "'
set tmp_env TMP(random)
read --silent $tmp_env -p 'echo "Jira password: "'

# Dereference once
set password_env (eval "echo \$"(echo $tmp_env))

set -xg JIRA_AUTH "Basic "(echo -n $JIRA_USER:$password_env | base64)
set -e $tmp_env