#!/usr/bin/env fish

# This does some extra work to make the password be read into a temporary
# environment variable which is cleared

test "$_" = .; or test "$_" = "source"; or begin
  echo (status -f): needs to be sourced
  exit 1
end

read -x JIRA_USER -p 'echo "Jira username: "'
set tmp_env TMP(random)
read --silent $tmp_env -p 'echo "Jira API token: "'

# Dereference once
set password_env (eval "echo \$"(echo $tmp_env))

echo Testing auth...

set auth "$JIRA_USER:$password_env"
set test_url $JIRA_HOST/rest/gadget/1.0/currentUser
set http_code (curl -sI -w "%{http_code}" -u $auth $test_url -o /dev/null)

if test $http_code = 200
  echo Success. JIRA_AUTH is set correctly and should be saved to your ~/.profile.
  set -x JIRA_AUTH "Basic "(echo -n $auth | base64)
else
  echo "Check your username (might be your email) and token. Got http code $http_code"
end

set -e $tmp_env
