#!/usr/bin/env fish

# This does some extra work to make the password be read into a temporary
# environment variable which is cleared

test "$_" = .; or test "$_" = "source"; or begin
  echo (status -f): needs to be sourced
  exit 1
end

read -x JIRA_USER -p 'echo "Jira username: "'
set tmp_env TMP(random)
read --silent $tmp_env -p 'echo "Jira API token: "'

# Dereference once
set password_env (eval "echo \$"(echo $tmp_env))

echo Testing auth...
set status_code (curl -sI -u $JIRA_USER:$password_env $JIRA_HOST/rest/gadget/1.0/currentUser | head -1 | coln 2)
if test $status_code = 200
  echo Success. JIRA_AUTH is set correctly and should be saved to your ~/.profile.
  set -x JIRA_AUTH "Basic "(echo -n $JIRA_USER:$password_env | base64)
else
  echo Check your username and token. Got status code $status_code
end

set -e $tmp_env
